### PR TITLE
Fix #22 and allow `null` values in JSON when interoperating with Swift

### LINKED ISSUE #22: Error: Cannot find interface declaration for NSObject in JSONAPIErrorResource.h (Xcode 7)
I got this error while using the library "as-is" (no CocoaPods) with Xcode 7. The error _could_ be coming from the absence of .pch file in the project.

The error can be fixed by adding the declarations for NSObject to the offending header. 
i.e.: adding
```
@import Foundation;
```
to JSONAPIErrorResource.h

### PR DESCRIPTION
**Pull request by christianklotz**
Besides adding the missing import so the classes compile successfully after importing them to a project this also includes a fix for explicitly set `null` values in JSON. When the data is parsed this turns into `NSNull` which isn’t equal to nil. Setting the attribute to `NSNull` leads to a type mismatch so it needs to be included in the comparison so that scenario can be prevented.

### CODE REVIEW

**Comment by joshdholtz** [comment]
@christianklotz Uggghhhh, `NSNull` is my least favorite thing ever.

File: Classes/JSONAPIResourceParser.m [hunk 1]
```diff
@@ -205,7 +205,7 @@ + (void)set:(NSObject <JSONAPIResource> *)resource withDictionary:dictionary {
             
         } else {
             id value = [attributes objectForKey:[property jsonName]];;
-            if (nil == value) {
+            if ((id)[NSNull null] == value) {
```
Comment (joshdholtz) [inline Classes/JSONAPIResourceParser.m]: @christianklotz Should be be keeping the check for `nil` but also check for `NSNull`?

Comment (christianklotz) [inline Classes/JSONAPIResourceParser.m]: The check I introduced works for nil as well :)

Comment (joshdholtz) [inline Classes/JSONAPIResourceParser.m]: @christianklotz Oh perfect!

**Comment by joshdholtz** [comment]
@christianklotz Thanks for the contribution!

**Comment by christianklotz** [comment]
Pleasure :)
